### ISSUE TITLE
New Repo

### ISSUE THREAD

**Issue by MrLuisAmador** [reactwithus/website#1]
It's about time that you added a new repo. Interested to see what will come out of this build.

**Comment by michelmarrache** [comment]
Well! Well! Well! It's good to hear from you man. Stay tuned because there's a lot of good things coming. I see you're working with WordPress, but aside from that are working with any JS frameworks?

**Comment by MrLuisAmador** [comment]
There's a new JS framework every other week. Lol! I'm playing around with
React and Angular 2. I still don't know which one will stick around and be
useful in my career.

I'm working on rebuilding my portfolio site with React and hooking into
WordPress by the new API.

I'm working for an agency so I haven't been able to get away from WordPress
or applying a JS framework to one of our projects.

I'm kinda over working for agencies and will pick a start up on my next
job. That way I can use new technologies.
